import { StaticImageData } from "next/image";

import Launch from "../../../../../public/imgs/plan-launch.svg";
import Design from "../../../../../public/imgs/plan-design.svg";
import Develop from "../../../../../public/imgs/plan-develop.svg";
import Idea from "../../../../../public/imgs/camera-man.svg";

export const contentMap: Record<
  "Idea" | "Design" | "Develop" | "Launch",
  { title: string[]; description: string[]; image: StaticImageData }
> = {
  Idea: {
    title: ["Your", "vision", "is", "unique"],
    description: [
      "Nurture",
      "Your",
      "Idea",
      "into",
      "a",
      "Blueprint",
      "for",
      "Success",
      "with",
      "our",
      "strategic",
      "insights",
      "and",
      "industry",
      "expertise",
      "Your",
      "vision",
      "is",
      "unique",
      "let's",
      "us",
      "shape",
      "it",
    ],
    image: Idea,
  },
  Design: {
    title: ["Crafting", "the", "blueprint", "for", "success"],
    description: [
      "Design",
      "is",
      "more",
      "than",
      "aesthetics",
      "it's",
      "about",
      "creating",
      "user",
      "experiences",
      "that",
      "resonate",
      "and",
      "convert",
      "Our",
      "design",
      "experts",
      "shape",
      "your",
      "vision",
      "into",
      "a",
      "stunning",
      "reality",
    ],
    image: Design,
  },
  Develop: {
    title: ["Turning", "blueprints", "into", "reality"],
    description: [
      "We",
      "breathe",
      "life",
      "into",
      "designs",
      "building",
      "robust",
      "platforms",
      "ready",
      "to",
      "disrupt",
      "markets",
      "Harness",
      "the",
      "experience",
      "of",
      "our",
      "development",
      "team",
      "to",
      "bring",
      "your",
      "Concept",
      "to",
      "Life",
    ],
    image: Develop,
  },
  Launch: {
    title: ["Your", "launchpad", "to", "the", "market"],
    description: [
      "Launching",
      "is",
      "just",
      "the",
      "beginning",
      "we",
      "ensure",
      "your",
      "product",
      "makes",
      "a",
      "splash",
      "and",
      "keeps",
      "making",
      "waves",
    ],
    image: Launch,
  },
};

export const words = [
  "From",
  "Spark",
  "to",
  "Spotlight:",
  "we",
  "take",
  "you",
  "every",
  "step",
  "of",
  "the",
  "way",
  "to",
  "success",
];
