export const data = [
  {
    id: 1,
    headText: "Experience",
    subText: [
      "Decades",
      "of",
      "collective",
      "wisdom.",
      "Leverage",
      "our",
      "experience",
      "to",
      "avoid",
      "common",
      "pitfalls",
      "and",
      "accelerate",
      "your",
      "business",
      "growth.",
    ],
  },
  {
    id: 2,
    headText: "Cost Savings",
    subText: [
      "Maximising",
      "impact,",
      "minimising",
      "costs",
      "efficiency",
      "is",
      "key.",
      "We",
      "provide",
      "cost-effective",
      "solutions",
      "without",
      "compromising",
      "on",
      "quality.",
    ],
  },
  {
    id: 3,
    headText: "Quick Support",
    subText: [
      "We",
      "are",
      "your",
      "reliable",
      "partner",
      "always",
      "there",
      "when",
      "you",
      "need",
      "us",
      "ensuring",
      "smooth",
      "operations",
      "at",
      "every",
      "stage",
      "of",
      "your",
      "growth",
    ],
  },
];

export const words = [
  "Your",
  "best",
  "call",
  "for",
  "B2B/B2C",
  "product",
  "innovation",
];
